---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[maven] "
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[maven] "
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
